### PR TITLE
While porting sniproxy to FreeBSD, I've notice wrong location of PID

### PR DESCRIPTION
**Pull request by krionbsd**
file. Move PID to /var/run as mentioned in man page.

### CODE REVIEW

**Comment by dlundquist** [comment]
@krionbsd I had placed it in /var/tmp because I assumed that would be present on every system. Is /var/run a present on all BSDs? and writable by non-privileged users? If so I see problem with this change. I'll merge this once I have confirmation? I'll check on OpenBSD if I don't hear back in a few days.

**Comment by jornane** [comment]
FWIW, /var/run also exists on NetBSD, it is not writable by non-privileged users. In other words, the same as FreeBSD.

**Comment by dlundquist** [comment]
Thank you, I figured it was closer to OpenBSD. There are two features which
I believe are disabled on FreeBSD: transparent proxy mode and the accept4
optimization. Please let me know if these can be easily supported.

-Dustin

**Comment by dlundquist** [comment]
Merged

**Pull request closed without merging**
