### PR TITLE
getpwnam only sets errno on an actual error

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by Habbie** [comment]
The title of this pull request is wrong and thus so is the patch. Will update.

**Comment by Habbie** [comment]
Fixed.

**Comment by dlundquist** [comment]
The Linux man page indicates:

> Return Value
> 
> The getpwnam() and getpwuid() functions return a pointer to a passwd structure, or NULL if the matching entry is not found or an error occurs.

So, checking if the return value is NULL should be sufficient. I agree this improves the user experience in the case that they enter an invalid user name in the configuration. Out of curiosity, what OS where did you encounter the case the `getpwnam` returned a non-NULL value in the event of an error?

**Comment by Habbie** [comment]
I'm not aware of any OS that returns non-NULL in case of error. It's about, theoretically, OSes that don't reset `errno` to zero on 'user not found' without error. Indeed it is about improving the user experience - before this patch, entering an unknown user would lead to `getpwnam(): Success` or the like which indeed is quite confusing. In fact, my coworker running into that is how I got to writing this patch.

Thank you for merging, and thank you for sniproxy!

**Pull request merged**
